### ISSUE TITLE
The errors occur when execute install.sh (http://prntscr.com/eb5oak)

### ISSUE THREAD

**Issue by ahonymous** [geekhub-php/serve-seattle#10]

**Comment by smagolexandr** [comment]
We know about this issue. It will be fixed soon.

**Comment by spolischook** [comment]
@smagolexandr please uncomment and fix this line https://github.com/geekhub-php/serve-seattle/blob/dev/.travis.yml#L16 after fix

**Comment by smagolexandr** [comment]
fixed #16
